#!/bin/sh
#
# Start bcm2835 audio driver
#

case "$1" in
  start)
        echo -n "Starting bcm2835 audio driver: "
        modprobe snd-bcm2835
        echo "OK"
        ;;
  stop)
        echo -n "Stopping bcm2835 audio driver: "
        rmmod snd-bcm2835
        echo "OK"
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
